### ISSUE TITLE
Is "free()" right here?

### ISSUE THREAD

**Issue by polettix** [pvigier/MyGAL#4]
With reference to this line (also something similar at line 64 shortly after):

https://github.com/pvigier/MyGAL/blob/03e1fa7938c7b8bab212df556bb56b0e1310a4cb/include/MyGAL/Beachline.h#L43

I wonder whether the `free` is out of place. From what my rusty memory tells me, it is supposed to be used only once and only on memory that has been previously allocated "the C way" (i.e. not with `new` but `malloc`/`calloc`). Looking at the initialization (root pointing the same as nil) it seems just something waiting to explode.

**Comment by pvigier** [comment]
Hi,

This `free` does not correspond to the `free` of the C standard library as `<cstdlib>` is not included, but to the `free` member function declared at line 469:

https://github.com/pvigier/MyGAL/blob/03e1fa7938c7b8bab212df556bb56b0e1310a4cb/include/MyGAL/Beachline.h#L469

Best,
Pierre

**Comment by pvigier** [comment]
By the way, i plan to rewrite `Beachline` using `std::set` instead of rewriting my own Red-Black tree implementation but I did not find the time yet.

**Comment by polettix** [comment]
D'oh, I didn't figure this out... thanks for pointing out. I'd humbly suggest a slight rename to "free_tree" or something like this, just for the next casual reader like me :-)

**Comment by pvigier** [comment]
Noted! I will improve that at the next update.
